# Default values for scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

images:
  nginx:
    name: nginx
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 128Mi
        cpu: 1000m
  app:
    name: app
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 128Mi
        cpu: 1000m

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts:
    - host: scanner.defihelper.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: scanner-tls
      hosts:
        - scanner.defihelper.io

broker:
  maxReplicas: 10
  maxReadyMessagesForHpa: 500
  process:
    labels:
      app: app
      component: broker
      environment: prod
      queue: process
    queues:
      queue:
        name: queue
        command: '"/bin/sh","-c","ln -s ./configuration/.env ./.env && npm run queue-consume -- -q scanner_tasks_default"'
        replicas: 1
        resources:
          requests:
            memory: 2048Mi
            cpu: 1
          limits:
            memory: 4096Mi
            cpu: 2
        nodeSelector:
          group_name: "apps-jobs"
        tolerations:
          - key: node-role.kubernetes.io/apps-jobs
            operator: "Equal"
            value: "true"
            effect: NoSchedule

handlers:
  nodeSelector:
    group_name: "apps-jobs"
  tolerations:
    - key: node-role.kubernetes.io/apps-jobs
      operator: "Equal"
      value: "true"
      effect: NoSchedule
  labels:
    app: scanner
    component: cronHandler
    environment: prod
  resources:
    requests:
      memory: 128Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 300m
  schedules:
    queue-deferred:
      command: '"/bin/sh","-c","ln -s ./configuration/.env ./.env && npm run queue-deferred"'
      schedule: "* * * * *"
#    hour:
#      command: '"/bin/sh","-c","ln -s ./configuration/.env ./.env && npm run tool stuckInProcessTasksRestarter"'
#      schedule: "0 * * * *"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nodeSelector:
  group_name: "apps-web"
tolerations:
  - key: node-role.kubernetes.io/apps-web
    operator: "Equal"
    value: "true"
    effect: NoSchedule
affinity: {}
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
